/// Flutter icons NavIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavIcons
///      fonts:
///       - asset: fonts/NavIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NavIcons {
  NavIcons._();

  static const _kFontFam = 'NavIcons';
  static const String _kFontPkg = null;

  static const IconData nav_car = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_more = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_study = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_test = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_sign = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_row_right = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_row_left = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nav_back = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
